config/routes.rb
Rails.application.routes.draw do

  resources :conversations

  root to: 'locations#index'

  post '/users/:user_id/reviews/new' => 'reviews#create'
  get '/users/:user_id/reviews/test' => 'reviews#test'
  post 'users/:id' => 'users#update'

  resources :sessions, only: [:new, :create, :destroy]
  
  resources :users do
    resources :reviews, only: [:edit, :update]
    resources :exchanges
    resources :conversations, path: 'mail'
  end

  match '/signup',      to: 'users#new',                via: 'get'

  match '/signin',      to: 'sessions#new',             via: 'get'
  match '/signout',     to: 'sessions#destroy',         via: 'delete'

  match '/location/posts',	to: 'locations#search',			via: 'post'   
  

  match '/dashboard', to: 'users#dashboard',            via: 'get'

 
  get 'twilio/sms' => 'twilio#sms'
 

end

app/models/exchange.rb
class Exchange
  include Mongoid::Document
  include Mongoid::Timestamps

  default_scope -> { order(created_at: :desc) }

  has_and_belongs_to_many :users

  field :provider_id, type: BSON::ObjectId
  field :seeker_id, type: BSON::ObjectId

  field :seeker_accept_exchange, type: Boolean
  field :provider_accept_exchange, type: Boolean  
  field :seeker_confirm_interaction, type: Boolean
  field :provider_confirm_interaction, type: Boolean

  field :provider_review_for_seeker_id, type: BSON::ObjectId
  field :seeker_review_for_provider_id, type: BSON::ObjectId

  field :completed, type: Boolean


  # Special date/time field to base expirations on.
  field :expirable_created_at, type: Time

  # TTL index on the above field. Need to run  rake db:mongoid:create_indexes
  index({expirable_created_at: 1}, {expire_after_seconds: 1.month})


  before_create :initialization
  def initialization
  	self.expirable_created_at = Time.now
  	self.seeker_accept_exchange = false
  	self.provider_accept_exchange = false
  	self.seeker_confirm_interaction = false
  	self.provider_confirm_interaction = false
  	self.completed = false
  	return true
  end


  def provider
    User.find(self.provider_id)
  end

  def seeker
    User.find(self.seeker_id)
  end

  def provider_review_for_seeker
    Review.find(self.provider_review_for_seeker_id)
  end

  def seeker_review_for_provider
    Review.find(self.seeker_review_for_provider_id)
  end

  def set_complete
    self.update_attribute(:completed, 1)
    self.update_attribute(:expirable_created_at, nil)
    self.seeker_accept_exchange = true
    self.provider_accept_exchange = true
    self.seeker_confirm_interaction = true
    self.provider_confirm_interaction = true
  end

end

app/controllers/exchanges_controller.rb
class ExchangesController < ApplicationController

  def new
    get_provider_seeker
    if current_user_type == 'provider'
      render 'new_for_provider'
    else
      render 'new_for_seeker'
    end
  end


  def update
    signed_in_user
    @exchange = Exchange.find(params[:id])

    if (@exchange.seeker_id == current_user.id || @exchange.provider_id == current_user.id)

      if params[:accept]
        @exchange.update_attribute(:"#{current_user_type}_accept_exchange", true)
      elsif params[:confirm]
        @exchange.update_attribute(:"#{current_user_type}_confirm_interaction", true)
      end

      if !@exchange.completed && @exchange.seeker_confirm_interaction && @exchange.provider_confirm_interaction
        @exchange.set_complete
        create_new_review(@exchange.seeker,@exchange.provider)
        create_new_review(@exchange.provider,@exchange.seeker)
      end

      redirect_to user_exchange_path(params[:user_id],@exchange)

    else
      not_a_participant
    end
  end


  def show
    signed_in_user
    @exchange = Exchange.find(params[:id])
    @provider = @exchange.provider
    @seeker = @exchange.seeker
    if @exchange.seeker_id == current_user.id
      render 'show_for_seeker'
    elsif @exchange.provider_id == current_user.id
      render 'show_for_provider'
    else
      not_a_participant
    end
  end


  def create
    get_provider_seeker 
    @exchange = Exchange.create!(provider_id: @provider.id, seeker_id: @seeker.id)
    @exchange.update_attribute(:"#{current_user_type}_accept_exchange", true)
    @seeker.exchanges.push(@exchange)
    @provider.exchanges.push(@exchange)
    redirect_to user_exchange_path(params[:user_id],@exchange)
  end



  private

    def get_provider_seeker
      signed_in_user
      @user = User.find(params[:user_id])
      if current_user.provider? && @user.seeker?
        @provider = current_user
        @seeker = @user
      elsif current_user.seeker? && @user.provider?
        @seeker = current_user
        @provider = @user
      else
        render 'error'
      end
    end

    def current_user_type
      if current_user.provider? then 'provider' else 'seeker' end
    end

    def not_a_participant
      flash[:warning] = "Sorry only participants can see this page"
      redirect_to user_path(params[:user_id])
    end

    def create_new_review(reviewer,recipient)
        new_review = Review.new(reviewer_id: reviewer.id, recipient_id: recipient.id)
        recipient.reviews.push(new_review)
        new_review.save(validate: false)
        @exchange.update_attribute(:"#{reviewer.user_type}_review_for_#{recipient.user_type}_id", new_review.id)
        #Notifier.new_review(reviewer,recipient,new_review).deliver
    end


end

app/views/exchanges/_completed_exchange.html.haml
Interacted with  
= link_to "#{completed_exchange.send(user_type).name}", user_path(completed_exchange.send(user_type))
#{time_ago_in_words(completed_exchange.updated_at)} ago.
%br

app/views/exchanges/_uncompleted_exchange.html.haml
= link_to "Exchange", user_exchange_path(uncompleted_exchange.send(user_type), uncompleted_exchange)
with 
= link_to "#{uncompleted_exchange.send(user_type).name}", user_path(uncompleted_exchange.send(user_type))
%br

app/views/exchanges/error.html.erb
Sorry, only non-providers can submit help requests to providers.

app/views/exchanges/new_for_provider.html.haml
.pure-g.grid-columns-container
  .pure-u-1-8.side-columns
  .pure-u-3-4.login-box-positioner
    .sign-up-box.sign-up-column
      %h1 Would you like to offer help to #{@seeker.name}?
      = button_to "Confirm", user_exchanges_path, class: "login-submit-button"
  .pure-u-1-8.side-columns

app/views/exchanges/new_for_seeker.html.haml
.pure-g.grid-columns-container
  .pure-u-1-8.side-columns
  .pure-u-3-4.login-box-positioner
    .sign-up-box.sign-up-column
      %h1 Would you like to send a help request to #{@provider.name}?
      = button_to "Confirm", user_exchanges_path, class: "login-submit-button"
  .pure-u-1-8.side-columns
      

app/views/exchanges/show_for_provider.html.haml
.pure-g.grid-columns-container
  .pure-u-1-8.side-columns
  .pure-u-3-4.login-box-positioner
    .sign-up-box.sign-up-column
      - if @exchange.completed
        %h1
          You have finished helping #{@seeker.name}.

        - if @exchange.provider_review_for_seeker.completed
          %h1
            You have left #{@seeker.name} a review. Thank you!
        - else
          %div
            If you have time, please write a review about your experience with #{@seeker.name}. This helps other people like you navigate TransHousing safely.
          = link_to "Write a review", edit_user_review_url(@seeker, @exchange.provider_review_for_seeker), class: "login-submit-button"

      - elsif !@exchange.provider_accept_exchange
        %h1
          #{@seeker.name} has sent a help request!

        %div
          Click the button below to accept #{@seeker.name}'s request.

        %div
          = link_to "Accept exchange", user_exchange_path(@seeker, @exchange, accept: true), method: :patch, class: "login-submit-button"

      - elsif !@exchange.seeker_accept_exchange 
        %h1
          You have offered to help #{@seeker.name}.

        %div
          The next step is for #{@seeker.name} to confirm your offer. You will receive a notification at that time.

      - elsif !@exchange.provider_confirm_interaction

        %h1
          You have an active help request with #{@seeker.name}.

        %div
          Once you have completed your request with #{@seeker.name}, please come back to confirm your interaction occurred. Once both parties have confirmed the interaction, you will be able to leave reviews for each other.

        %div
          = link_to "Confirm Interaction", user_exchange_path(@seeker, @exchange, confirm: true), method: :patch, class: "login-submit-button"


      - elsif !@exchange.seeker_confirm_interaction

        %h1
          You have confirmed your interaction with #{@seeker.name}.

        %div
          Once #{@seeker.name} confirms your interaction, you will be able to leave reviews for each other.
  .pure-u-1-8.side-columns
          

app/views/exchanges/show_for_seeker.html.haml
.pure-g.grid-columns-container
  .pure-u-1-8.side-columns
  .pure-u-3-4.login-box-positioner
    .sign-up-box.sign-up-column
      - if @exchange.completed
        %h1
          Your help request to #{@provider.name} is completed.

        - if @exchange.seeker_review_for_provider.completed
          %h1
            You have left #{@provider.name} a review. Thank you!
        - else
          %div
            If you have time, please write a review about your experience with #{@provider.name}. This helps other people like you navigate TransHousing safely.
          = link_to "Write a review", edit_user_review_url(@provider, @exchange.seeker_review_for_provider), class: "login-submit-button"


      - elsif !@exchange.seeker_accept_exchange
        %h1
          #{@provider.name} has offered to help!

        %div
          Click the button below to accept #{@provider.name}'s offer.

        %div
          = link_to "Accept offer", user_exchange_path(@provider, @exchange, accept: true), method: :patch, class: "login-submit-button"


      - elsif !@exchange.provider_accept_exchange 
        %h1
          You have submitted a help request to #{@provider.name}.

        %div
          The next step is for #{@provider.name} to confirm your request. You will receive a notification at that time.


      - elsif !@exchange.seeker_confirm_interaction

        %h1
          You have an active help request with #{@provider.name}.

        %div
          Once you have completed your request with #{@provider.name}, please come back to confirm your interaction occurred. Once both parties have confirmed the interaction, you will be able to leave reviews for each other.

        %div
          = link_to "Confirm Interaction", user_exchange_path(@provider, @exchange, confirm: true), method: :patch, class: "login-submit-button"


      - elsif !@exchange.provider_confirm_interaction

        %h1
          You have confirmed your interaction with #{@provider.name}.

        %div
          Once #{@provider.name} confirms your interaction, you will be able to leave reviews for each other.
  .pure-u-1-8.side-columns
          