config/routes.rb
Rails.application.routes.draw do

  resources :conversations

  root to: 'locations#index'

  post '/users/:user_id/reviews/new' => 'reviews#create'
  get '/users/:user_id/reviews/test' => 'reviews#test'
  post 'users/:id' => 'users#update'

  resources :sessions, only: [:new, :create, :destroy]
  
  resources :users do
    resources :reviews, only: [:edit, :update]
    resources :exchanges
    resources :conversations, path: 'mail'
  end

  match '/signup',      to: 'users#new',                via: 'get'

  match '/signin',      to: 'sessions#new',             via: 'get'
  match '/signout',     to: 'sessions#destroy',         via: 'delete'

  match '/location/posts',	to: 'locations#search',			via: 'post'   
  

  match '/dashboard', to: 'users#dashboard',            via: 'get'

 
  get 'twilio/sms' => 'twilio#sms'
 

end

app/views/notifier/new_message.html.haml
%h1 Hi, #{@receiver.name}!

%h2 You have a new message from #{@sender.name}.

\--
.div #{@message.text}
\--

/Click to
/= link_to("reply", user_conversation_path(user_id: @receiver.id.to_s, id: @thread.to_s))

/Visit your
/= link_to("account", user_path(id: @receiver.id.to_s))

app/views/notifier/new_message.text.haml
Hi, #{@receiver.name}!

You have a new message from #{@sender.name}.

#{@message.text}

/Click the link to
/= link_to("Reply", user_conversation_path(user_id: @receiver.id.to_s, id: @thread.to_s))

/Visit your 
/= link_to("User Account", user_path(id: @receiver.id.to_s))

app/views/notifier/new_review.html.haml
%h1 Hi, #{@sender.name}!

%h2 Please leave a review for #{@receiver.name}.

%div
  = link_to("Click here to post your review.", edit_user_review_url(@receiver.id.to_s, @review.id.to_s))

%div
  Or navigate your browser to the following URL:
  = edit_user_review_url(@receiver.id.to_s, @review.id.to_s)

app/views/notifier/new_review.text.haml
Hi, #{@sender.name}!

Please leave a review for #{@receiver.name}.

= edit_user_review_url(@receiver.id.to_s, @review.id.to_s)

Visit your account at:
= user_url(@sender.id.to_s)

app/views/notifier/welcome.html.haml
%h1 Hi, #{@receiver.name}!

%h2 You have sucessfully signed up for TransHousing.

%div
/Visit your
/=link_to("User Account", user_path(id: @receiver.id.to_s))

app/views/notifier/welcome.text.haml
Hi, #{@receiver.name}!

You have sucessfully signed up for TransHousing.

/Visit your
/= link_to("User Account", user_path(id: @receiver.id.to_s))