config/routes.rb
Rails.application.routes.draw do

  resources :conversations

  root to: 'locations#index'

  post '/users/:user_id/reviews/new' => 'reviews#create'
  get '/users/:user_id/reviews/test' => 'reviews#test'
  post 'users/:id' => 'users#update'

  resources :sessions, only: [:new, :create, :destroy]
  
  resources :users do
    resources :reviews, only: [:edit, :update]
    resources :exchanges
    resources :conversations, path: 'mail'
  end

  match '/signup',      to: 'users#new',                via: 'get'

  match '/signin',      to: 'sessions#new',             via: 'get'
  match '/signout',     to: 'sessions#destroy',         via: 'delete'

  match '/location/posts',	to: 'locations#search',			via: 'post'   
  

  match '/dashboard', to: 'users#dashboard',            via: 'get'

 
  get 'twilio/sms' => 'twilio#sms'
 

end

app/models/user.rb
class User
  
  include Mongoid::Document
  include Mongoid::Attributes::Dynamic
  include ActiveModel::SecurePassword

  field      :name,                         type: String
  field      :is_provider,                  type: Boolean


  embeds_one :gender
  has_one    :contact,                      dependent: :delete
  has_one    :location,                     dependent: :delete

  embeds_one :preference_profile
  embeds_one :extended_profile

  embeds_one :food_resource
  embeds_one :shower_resource
  embeds_one :laundry_resource
  embeds_one :housing_resource
  embeds_one :transportation_resource
  embeds_one :buddy_resource
  embeds_one :misc_resource

  has_many   :reviews
  field      :number_reviews,               type: Integer
  field      :sum_rating,                   type: Float
  field      :average_rating,               type: Float

  has_and_belongs_to_many :exchanges

  has_many :conversations
  has_many :messages
  
  accepts_nested_attributes_for  :gender, :contact,
  :food_resource, :shower_resource, :laundry_resource,
  :housing_resource, :transportation_resource,
  :extended_profile,
  :buddy_resource, :misc_resource, :location
  
  validates_presence_of          :gender, :contact, :name,
  :food_resource, :shower_resource, :laundry_resource,
  :housing_resource, :transportation_resource,
  :buddy_resource
  
  validates_associated           :gender, :contact#
  
  
  field :remember_token,         type: String
  field :password_digest,        type: String
  
  has_secure_password
  before_create :create_remember_token, :initialization
  
  def pronoun(tense)
    standard_pronouns = { 
      "male" => 
      {"they" => "he",
        "them" => "him", 
        "their" => "his"},
      "female" => 
      {"they" => "she",
        "them" => "her", 
        "their" => "her"} }
    identity = self.gender[:identity].downcase
    standard_pronouns.has_key?(identity) ? standard_pronouns[identity][tense] : nil ||
      self.gender[tense.to_sym] ||
      tense
  end
  
  # Returns true if JSON from mailgun API call contains true "is_valid" field
  # Description of validator in Mailgun docs; multimap doesn't work for Ruby 2
  def mailgun_valid?(email)
    #url_params = Multimap.new
    url_params = {}
    url_params[:address] = email
    query = url_params.collect {|k,v| "#{k.to_s}=#{CGI::escape(v.to_s)}"}.join("&")
    response = 
      RestClient.get "https://api:pubkey-d005c8be2308c95c34d7b9924a2b7fa7@api.mailgun.net/v3/address/validate?#{query}"
    hash = JSON.parse response
    hash["is_valid"]
  end
  
  def they
    self.pronoun "they"
  end

  def them
    self.pronoun "them"
  end

  def their
    self.pronoun "their"
  end
  
  def provider?
    self.is_provider
  end
  
  def seeker?
    !self.is_provider
  end

  def food?
    self.food_resource[:currently_offered]
  end

  def shower?
    self.shower_resource[:currently_offered]
  end

  def laundry?
    self.laundry_resource[:currently_offered]
  end

  def housing?
    self.housing_resource[:currently_offered]
  end

  def transportation?
    self.transportation_resource[:currently_offered]
  end

  def buddy?
    self.buddy_resource[:currently_offered]
  end

  def misc?
    self.misc_resource && self.misc_resource[:currently_offered]
  end

  def prefs
    self.preference_profile
  end

  def email
    self.contact.email
  end

  def phone
    self.contact.phone
  end

  def self.all_user_type_filters
    return ['provider','seeker']
  end

  def self.all_resource_filters
    return ['housing','laundry','food','buddy','shower','transportation']
  end

  def self.providers
    User.where(is_provider: true)
  end

  def self.seekers
    User.where(is_provider: false)
  end

  def authored_reviews
    Review.where(reviewer_id: self.id).all
  end

  def pending_exchanges
    self.exchanges.select { |n| !n.seeker_accept_exchange || !n.provider_accept_exchange }
  end

  def active_exchanges
    self.exchanges.select { |n| n.seeker_accept_exchange && n.provider_accept_exchange && !n.completed }
  end

  def user_type
    if self.provider? then "provider" else "seeker" end
  end

  def user_type_complement
    if self.provider? then "seeker" else "provider" end
  end

  # Retrieve whether or not a user has enabled receipt of 
  # new message notifications by text message.
  # Default is false. 
  def receives_message_notifs_by_text?
    if self.prefs.nil? || self.prefs.message_notifs.nil? ||
        self.prefs.message_notifs[:text].blank? ||
        self.prefs.message_notifs[:text] == false
      false
    elsif self.prefs.message_notifs[:text] == true
      true
    end
  end

  # Retrieve whether or not a user has enabled receipt of 
  # new message notifications by email message.
  # Default is true. 
  def receives_message_notifs_by_email?
    if self.prefs.nil? || self.prefs.message_notifs.nil? ||
        self.prefs.message_notifs[:email].blank? ||
        self.prefs.message_notifs[:email] == true
      true
    elsif self.prefs.message_notifs[:email] == false
      false
    end
  end

  # Retrieve whether or not a user has enabled receipt of 
  # new dashboard (request/offers/reviews) notifications by 
  # text message.
  # Default is false. 
  def receives_dashboard_notifs_by_text?
    if self.prefs.nil? || self.prefs.dashboard_notifs.nil? ||
       self.prefs.dashboard_notifs[:text].blank? ||
       self.prefs.dashboard_notifs[:text] == false
      false
    elsif self.prefs.dashboard_notifs[:text] == true
      true
    end
  end

  # Retrieve whether or not a user has enabled receipt of 
  # new dashboard (request/offers/reviews) notifications by 
  # email message.
  # Default is true. 
  def receives_dashboard_notifs_by_email?
    if self.prefs.nil? || self.prefs.dashboard_notifs.nil? ||
        self.prefs.dashboard_notifs[:email].blank? ||
        self.prefs.dashboard_notifs[:email] == true
      true
    elsif self.prefs.dashboard_notifs[:email] == false
      false
    end
  end

  def User.new_remember_token
    SecureRandom.urlsafe_base64
  end

  def User.digest(token)
    Digest::SHA1.hexdigest(token.to_s)
  end

  def self.search(search)
    if search
      any_of({name: /#{search}/i}, {city: /#{search}/i})
    else
      self.all.to_a
    end
  end

  def self.resources_list
    ["Housing",
     "Food",
     "Shower",
     "Laundry",
     "Transportation"]
  end

  ###################################################################################
  # These are only used for fabrication - in practice, we will use cached values
  # in the fields of User model
  def calculate_number_reviews
    self.reviews.length
  end

  def calculate_sum_rating
    if self.reviews.empty? then 0
    else self.reviews.map {|r| r.rating}.reduce(:+) end
  end

  def calculate_average_rating
    if self.reviews.empty? then 0
    else (self.calculate_sum_rating.to_f / self.calculate_number_reviews).round(1) end
  end
  ####################################################################################


  # def self.numerical_options
  #   ["1","2","3","4","5","6","7","8","9","10"]
  # end
  
  # not uself filter functions
  # def self.integer_from_options_list(options_list)
  #   # convert options list given by radio buttons into one-hot integer
  #   resources = 0;
  #   if options_list
  #     options_list.each do |option|
  #       resources += 2 ** option.to_i
  #     end
  #   end

  #   resources
  # end

  # def self.find_with_filters(filters)

  #   filtered_users = User.all

  #   # if filters[:city] && filters[:city].length > 0
  #   #   filtered_users = filtered_users.near(filters[:city], 30)
  #   # end

  #   if filters[:resources]
  #     resources = User.integer_from_options_list(filters[:resources])
  #     # filtered_users = filtered_users.where({"resources & ? = ?", resources, resources})
  #   end

  #   filtered_users
  # end

  # def set_resources_from_options_list!(options_list)
  #   self.resources = User.integer_from_options_list(options_list)
  # end

  # def boolean_array_from_resources_integer
  #   [].tap do |resources_list|
  #     User.resources_list.length.times do |order|
  #       resources_list << (self.resources & 2 ** order > 0)
  #     end
  #   end
  # end

  private
  
  def create_remember_token
    self.remember_token = User.digest(User.new_remember_token)
  end
  
  def init_reviews
    self.number_reviews = 0
    self.average_rating = 0
    self.sum_rating = 0
  end

  def initialization
    init_reviews
    self.preference_profile ||= PreferenceProfile.new
    self.extended_profile ||= ExtendedProfile.new
  end
  
end

app/controllers/users_controller.rb
class UsersController < ApplicationController
  include Geokit::Geocoders
  
  def new
    if signed_in?
      redirect_to root_url
    end
    @user = User.new
    @user.build_contact
    @user.build_location(session[:location])
    @user.build_gender

    @user.build_food_resource
    @user.build_shower_resource
    @user.build_laundry_resource
    @user.build_housing_resource
    @user.build_transportation_resource
    @user.build_buddy_resource
  end

  # should move part of this to model
  def create
    @user = User.new(user_params)
	session[:signup] = true
	if @user.location && @user.location[:city] != ""
		@geokitResult = Geokit::Geocoders::GoogleGeocoder.geocode(
			@user.location[:city]+ " " + @user.location[:state])
		if @geokitResult.success
			@user.location[:c] = [@geokitResult.lng, @geokitResult.lat]
		elsif session[:coordinates]
		    @user.location[:c] = session[:coordinates].map &:to_f
		else 
			@user.location[:c] = [-41.3111, 72.9267]
		end
	elsif session[:coordinates]
		@user.location[:c] = session[:coordinates].map &:to_f		
	else 
		@user.location[:c] = [-41.3111, 72.9267]
    end
    
    if verify_recaptcha(model: @user, message: "Please retry the captcha.") && @user.save
       # Iff phone # given, make sure it's correct (but let continue)
      if !@user.contact[:phone].blank?
        @user.contact[:phone] = GlobalPhone.normalize(@user.contact[:phone])
        @phone = @user.contact[:phone]
        if !GlobalPhone.validate(@phone)
          # Put in flash alert about invalid United States phone #
          flash[:warning] = "Note: we were unable to automatically verify your phone number. Please check in your settings that it is correct."
        end
      end
      
      # Iff email addr given, make sure it's valid (but let continue)
      if !@user.contact[:email].blank?
        if !@user.mailgun_valid?(@user.contact[:email])
          flash[:warning] = "Note: we were unable to automatically verify your email address. Please check in your settings that it is correct."
        end
      end

      # Send a welcome email if we're in production
      if Rails.env.production?
        Notifier.welcome(@user).deliver
      end
      
      sign_in @user
      flash[:success] = "Welcome to TransHousing!"
      redirect_to @user
    else
      # If the captcha error is the only one, only give a captcha error.
      if @user.errors.messages.except(:base).all? { |k,v| v.empty? }
        error_message = @user.errors.messages[:base].first
      else 
        error_message = "Some of your input was invalid or missing." + 
        "Those fields are highlighted in red. " +
        "Please fill all fields appropriately and retry the captcha."
      end
      flash.now[:error] = error_message
      render 'new'
    end
  end
  
  def edit
    @user = User.find(params[:id])
  end
  
  def update
    @user = User.find(params[:id])

    if @user.update_attributes(edit_user_params)
      flash[:success] = "Success!"
      redirect_to @user
    else
      flash.now[:error] = "Please correct highlighted errors and try again."
      render 'edit'
    end
  end

  def index
    @users = User.all
    @users = User.search(params[:search])

    if params[:users_filters]
      @users = User.find_with_filters(params[:users_filters])
    end
  end
  
  def show
    @user = User.find(params[:id])
    @reviews = @user.reviews
  end
  

  def dashboard
    signed_in_user
    @user = current_user
  end
  
  private
    def user_params
      params.require(:user).permit(
        :name,
        :is_provider,
        :password, :password_confirmation,
        gender_attributes:                  [:identity, :trans, :cp,
                                              :they, :their, :them],
        contact_attributes:                 [:email, :phone],
        location_attributes:                [:c,:zip,:city,:state],
        food_resource_attributes:           [:currently_offered],
        shower_resource_attributes:         [:currently_offered],
        laundry_resource_attributes:        [:currently_offered],
        housing_resource_attributes:        [:currently_offered],
        transportation_resource_attributes: [:currently_offered],
        buddy_resource_attributes:          [:currently_offered]
        )
    end

    def edit_user_params
      params.require(:user).permit(
        :name,
        :password, :password_confirmation,
        extended_profile_attributes:        [:profile_summary],
        contact_attributes:                 [:email, :phone],
        location_attributes:                [:c,:zip,:city,:state],
        food_resource_attributes:           [:currently_offered],
        shower_resource_attributes:         [:currently_offered],
        laundry_resource_attributes:        [:currently_offered],
        housing_resource_attributes:        [:currently_offered],
        transportation_resource_attributes: [:currently_offered],
        buddy_resource_attributes:          [:currently_offered],
        misc_resource_attributes:           [:currently_offered]
        )
    end
end

app/helpers/users_helper.rb
module UsersHelper
end

app/views/users/_signup.html.haml
-#
  %ul#sign-up-progress-bar
    %li.active Name
    %li
      Gender
      %ul
        %li Category
        %li Identity
        %li Pronouns
    %li Location
    %li 
      Resources
      %ul
        %li Position
        %li Food
        %li Shower
        %li Laundry
        %li Housing
        %li Transport
        %li Buddy
        %li Misc
    %li Contact
    %li Finish

.sign-up-box.sign-up-column

  = simple_form_for @user do |f|
    .step-1.wizard-page.wizard-current
      %h1 Welcome!
      We're so glad to see you here. Let's walk through making your account!
      %fieldset
        %h2.fs-title First things first: what's your name?
        = f.input :name, label: false, placeholder: "I am..."

      %button.wizard-forward{type: "button",id: "user_name_button", onclick: "th.validateAndAdvance($(this));"} Next
    .step-2.wizard-page
      = f.simple_fields_for :gender do |g|
        %fieldset.step-g-1.wizard-page
          %h2.fs-title
            Now, let's talk about gender. 
          Are you a transgender person, or otherwise under the trans* identity umbrella?
          .radio-form-container
            = g.collection_radio_buttons :trans, [[true, 'Yes!'] ,[false, 'Nope']], :first, :last, item_wrapper_class: "radio-container"
          %button.wizard-back{type: "button",onclick: "th.advanceWizard('g-1',0); th.advanceWizard(2,1);"} Back
          %button.wizard-forward{type: "button",id: "user_gender_attributes_trans_true_button",onclick: "th.validateAndAdvance($(this));"} Next
  
        %fieldset.step-g-2.wizard-page
          %h2.fs-title 
            What is your gender?
          = select_tag "binary_genders", options_for_select([ "Male", "Female" ], "Male")
          = select_tag "binary_trans_genders", options_for_select([ "Male", "Female", "Nonbinary" ], "Male")
          = select_tag "nonbinary_trans_genders", options_for_select(["Bigender","Agender","Genderqueer","Genderfluid","Just let me type it!"], "Genderqueer")
          = g.input :identity, label: false, input_html: { value: 'Male', placeholder: "I am..."}
          %button.wizard-back{type: "button",onclick: "th.advanceWizard('g-2','g-1')"} Back
          %button.wizard-forward{type: "button",id: "user_gender_attributes_identity_button",onclick: "th.validateAndAdvance($(this));"} Next

        %fieldset.step-g-3.wizard-page
          %h2.fs-title 
            So, are your pronouns 
            %span#they "he",
            %span#them "him", 
            %span#their "his"?
          .radio-form-container
            = g.collection_radio_buttons :cp, [[false, 'Yes'] ,[true, 'No']], :first, :last, item_wrapper_class: "radio-container"
          %button.wizard-back{type: "button",onclick: "th.advanceWizard('g-3','g-2')"} Back
          %button.wizard-forward{type: "button",id: "user_gender_attributes_cp_false_button",onclick: "th.validateAndAdvance($(this));"} Next
        %fieldset.step-g-4.wizard-page
          %h2.fs-title Please enter your pronouns.
          = g.input :they, label: false, placeholder: '"She/he/they" tense'
          = g.input :their, label: false, placeholder: '"Her/him/them" tense'
          = g.input :them, label: false, placeholder: '"Her/his/their" tense'
          %button.wizard-back{type: "button",onclick: "th.advanceWizard('g-4','g-3')"} Back
          %button.wizard-forward{type: "button",id: "user_gender_attributes_they_button",onclick: "th.validateAndAdvance($(this));"} Next
    .step-3.wizard-page
      = f.simple_fields_for :contact do |c|
        %fieldset
          %h2.fs-title Enter your phone, email, or both-- you can login with these later.
          = c.input :email, label: false, placeholder: "Email"
          = c.input :phone, label: false, placeholder: "Phone"
          %button.wizard-back{type: "button",onclick: "th.advanceWhereDecision('3')"} Back
          %button.wizard-forward{type: "button",id: "user_contact_attributes_email_button",onclick: "th.validateAndAdvance($(this));"} Next

    .step-4.wizard-page
      = f.simple_fields_for :location do |l|
        %fieldset
          %h2.fs-title Enter your location.
          Or anywhere reasonably close-- we just want to match you with the right people!
          = l.input :zip, label: false, placeholder: "zip"
          = l.input :city, label: false, placeholder: "city"
          = l.input :state, label: false, placeholder: "state"
          %button.wizard-back{type: "button",onclick: "th.advanceWizard('4','3')"} Back
          %button.wizard-forward{type: "button",id: "user_location_attributes_zip_button",onclick: "th.validateAndAdvance($(this));"} Next
        %div.mapcontainer 
          #map_canvas

    .step-5.wizard-page
      %fieldset
        %h2.fs-title Are you seeking help, or can you offer help?
        .radio-form-container
          = f.collection_radio_buttons :is_provider, [[true, 'I can help!'] ,[false, 'I need help!']], :first, :last, item_wrapper_class: "radio-container"
        %button.wizard-back{type: "button",onclick: "th.advanceWizard('5','4'); google.maps.event.trigger(map, 'resize');"} Back
        %button.wizard-forward{type: "button",id: "user_is_provider_true_button",onclick: "th.validateAndAdvance($(this));"} Next

    .step-6.wizard-page
      %fieldset
        %h2.fs-title#seeker-status-text What can you help with/offer?
        .resource
          = f.simple_fields_for :food_resource do |fr|
            %label Food
            .radio-form-container
              = fr.collection_radio_buttons :currently_offered, [[true, 'Yes'] ,[false, 'No']], 
                                                    :first, :last, item_wrapper_class: "radio-container", :checked => [false, 'No']
        .resource
          = f.simple_fields_for :shower_resource do |sr|
            %label A clean shower
            .radio-form-container
              = sr.collection_radio_buttons :currently_offered, [[true, 'Yes'] ,[false, 'No']], 
                                                    :first, :last, item_wrapper_class: "radio-container", :checked => [false, 'No']
        .resource
          = f.simple_fields_for :laundry_resource do |lr|
            %label Access to a laundry machine
            .radio-form-container
              = lr.collection_radio_buttons :currently_offered, [[true, 'Yes'] ,[false, 'No']], 
                                                    :first, :last, item_wrapper_class: "radio-container", :checked => [false, 'No']
        .resource
          = f.simple_fields_for :housing_resource do |hr|
            %label Somewhere to sleep
            .radio-form-container
              = hr.collection_radio_buttons :currently_offered, [[true, 'Yes'] ,[false, 'No']], 
                                                    :first, :last, item_wrapper_class: "radio-container", :checked => [false, 'No']
        .resource
          = f.simple_fields_for :transportation_resource do |tr|
            %label Transportation from place to place
            .radio-form-container
              = tr.collection_radio_buttons :currently_offered, [[true, 'Yes'] ,[false, 'No']], 
                                                    :first, :last, item_wrapper_class: "radio-container", :checked => [false, 'No']
        .resource
          = f.simple_fields_for :buddy_resource do |br|
            %label A buddy for mentorship and added safety in acquiring resources
            .radio-form-container
              = br.collection_radio_buttons :currently_offered, [[true, 'Yes'] ,[false, 'No']], 
                                                    :first, :last, item_wrapper_class: "radio-container", :checked => [false, 'No']

        %button.wizard-back{type: "button",onclick: "th.advanceWizard('6','5')"} Back
        %button.wizard-forward{type: "button",id: "user_food_resource_attributes_currently_offered_true_button",onclick: "th.validateAndAdvance($(this));"} Next

    .step-7.wizard-page
      %fieldset
        %h2.fs-title Fantastic!
        Just choose a password, and you're ready to get started!
        = f.input :password
        = f.input :password_confirmation
        = recaptcha_tags

        = f.button :submit, value: "Create my account!", id: "submit_signup",class: "wizard-forward"

        %button.wizard-back{type: "button",onclick: "th.advanceWizard('7','6')"} Back

app/views/users/dashboard.html.haml
.pure-g.login-column
  .pure-u-1-8.side-columns
  .pure-u-3-4.login-box-positioner
    .login-box.login-column

      %h3 Pending Exchanges

      - if @user.pending_exchanges.any?
        = render partial: "exchanges/uncompleted_exchange", collection: @user.pending_exchanges, locals: {user_type: @user.user_type_complement}
      - else
        No pending exchanges right now.

      %h3 Active Exchanges

      - if @user.active_exchanges.any?
        = render partial: "exchanges/uncompleted_exchange", collection: @user.active_exchanges, locals: {user_type: @user.user_type_complement}
      - else
        No active exchanges right now.


      %h3 Reviews to Finish
      - if @user.authored_reviews.uncompleted.any?
        Reminder: please complete the following reviews:
        = render partial: "reviews/uncompleted_review", collection: @user.authored_reviews.uncompleted
      - else
        Nobody to review right now.


      %h3 Past Reviews You've Written
      - if @user.authored_reviews.completed.any?
        = render partial: "reviews/authored_review", collection: @user.authored_reviews.completed
      - else
        You haven't written any reviews yet!


      %h3 History
      - if @user.exchanges.completed.any?
        = render partial: "exchanges/completed_exchange", collection: @user.exchanges.completed, locals: {user_type: @user.user_type_complement}
      - else
        You haven't interacted with anyone yet!

  .pure-u-1-8.side-columns

app/views/users/index.html.haml
- provide(:title, 'Find Users')

.pure-g.login-column
  .pure-u-1-8.side-columns
  .pure-u-3-4.login-box-positioner
    .page-content-box
      %h1 All Users
      %form#space-index-filter-form.sidebar-filters
        %h4.sidebar-section-header Resources
        .sidebar-section.group
          = checkbox_group collection: User.resources_list,
                               ul_class:   "checkbox-li",
                               html_name:  "users_filters[resources]"

        %input#user-index-sidebar-filter-button{ "type" => "submit", "value" => "Filter"}

      = form_tag users_path, :method => 'get' do
        = text_field_tag :search
        = submit_tag "Search"

      %ul.users
        - @users.each do |user|
          %li
            = link_to user.name, user

    
  .pure-u-1-8.side-columns

app/views/users/new.html.haml
/ Text-only Content Skeleton
.pure-g.login-column
  .pure-u-1-8.side-columns
  .pure-u-3-4.login-box-positioner
    = render 'signup'
  .pure-u-1-8.side-columns

app/views/users/show.html.haml
- provide :title, @user.name

.pure-g.grid-columns-container
  .pure-u-1-8.side-columns
  .pure-u-3-4.login-box-positioner
    #profile-page.sign-up-box.sign-up-column
      .pure-u-1
        - if !current_user.nil? && current_user != @user
          = link_to "Contact #{@user.name}", new_user_conversation_path(@user.id), class: "btn btn-primary wizard-forward" 

          - if current_user.seeker? && @user.provider?
            = link_to "Request help from #{@user.name}", new_user_exchange_path(@user.id), class: "btn btn-primary wizard-back", id: "request-help-button"

          - if current_user.provider? && @user.seeker?
            = link_to "Offer help to #{@user.name}", new_user_exchange_path(@user.id), class: "btn btn-primary wizard-back", id: "request-help-button"
        %h1#user-name.user-name{class: "header-username-#{gender_category(@user.gender[:identity])}"}
          = @user.name
      .pure-g
        .pure-u-1-4#profile-left-column
          %h2.user-status
            = @user.seeker? ? "Resource seeker" : "Resource provider"
          .user-resources
            - if @user.food?
              = icon("fa fa-cutlery fa-2x")
            - if @user.shower?
              = icon("fa fa-street-view fa-2x")
            - if @user.laundry?
              = icon("fa fa-tags fa-2x")
            - if @user.housing?
              = icon("fa fa-bed fa-2x")
            - if @user.transportation?
              = icon("fa fa-car fa-2x")
            - if @user.buddy?
              = icon("fa fa-users fa-2x")
          %div
            %span{class: "header-username-#{gender_category(@user.gender[:identity])}"}
              = "#{@user.gender[:trans] ? "#{@user.gender[:identity].capitalize}, Trans" : "Cis #{@user.gender[:identity].downcase}"}"
            .user-location
              = "#{@user.location.city}, #{@user.location.state}"
        .pure-u-3-4#profile-right-column
          %h2 About #{@user.name}
          - if @user.extended_profile.nil? || @user.extended_profile[:profile_summary].blank?
            - if current_user == @user
              You can edit your profile summary on
              = link_to "your settings page.", edit_user_path(current_user)
            - else
              #{@user.name} has not yet filled out #{@user.their} profile. Consider reaching out to #{@user.them} and helping #{@user.them} get started.
          - else
            = @user.extended_profile[:profile_summary]


      .pure-u-1#profile-bottom-section
        %h3.user-rating
        - if @user.number_reviews > 0
          Average Rating
          = get_stars(@user.average_rating)
          %h3 
            = "Reviews (#{@user.number_reviews})"
          %ol.reviews
            = render @reviews
        - else
          %h3 
            #{@user.name} does not yet have any reviews.
  .pure-u-1-8.side-columns