config/routes.rb
Rails.application.routes.draw do

  resources :conversations

  root to: 'locations#index'

  post '/users/:user_id/reviews/new' => 'reviews#create'
  get '/users/:user_id/reviews/test' => 'reviews#test'
  post 'users/:id' => 'users#update'

  resources :sessions, only: [:new, :create, :destroy]
  
  resources :users do
    resources :reviews, only: [:edit, :update]
    resources :exchanges
    resources :conversations, path: 'mail'
  end

  match '/signup',      to: 'users#new',                via: 'get'

  match '/signin',      to: 'sessions#new',             via: 'get'
  match '/signout',     to: 'sessions#destroy',         via: 'delete'

  match '/location/posts',	to: 'locations#search',			via: 'post'   
  

  match '/dashboard', to: 'users#dashboard',            via: 'get'

 
  get 'twilio/sms' => 'twilio#sms'
 

end

app/controllers/application_controller.rb
class ApplicationController < ActionController::Base
  # Prevent CSRF attacks by raising an exception.
  # For APIs, you may want to use :null_session instead.
  protect_from_forgery with: :exception
  include SessionsHelper
  
  #before_filter :login_required
  #protected

  	#def login_required
  	#	redirect_to root_url unless signed_in?
  	#end



  rescue_from Mongoid::Errors::DocumentNotFound, :with => :record_not_found

  def record_not_found
    #raise ActionController::RoutingError.new('Not Found')
    flash[:warning] = "Sorry, not found in database"
    redirect_to root_url
  end

  	
end

app/helpers/application_helper.rb
module ApplicationHelper


  def full_title(page_title)
    base_title = "TransHousing"
    if page_title.blank?
      base_title
    else
      "#{page_title} | #{base_title}"
    end
  end

  def icon(class_str)
    icon_class = "."+class_str.strip.split(" ").join(".")
    raw Haml::Engine.new("%i#{icon_class}").render.chop
  end

  def gender_category(user_gender_identity)
    if user_gender_identity.to_s.downcase != "male" &&
       user_gender_identity.to_s.downcase != "female"
      "nb"
    else
      user_gender_identity.to_s.downcase
    end
  end

  def gender_category_class
    "header-username-#{gender_category(current_user.gender[:identity])}"
  end

  def checkbox_group(options)
    # options hash must include :collection, :ul_class, and :html_name
    @ul = options
    render "shared/checkbox_group"
  end

  def select_given_options(options)
    @options = options
    render "shared/select_given_options"
  end

  def select_numerical_given_options(options)
    @options = options
    render "shared/select_numerical"
  end


  def get_stars(rating)
    counter = 0
    stars = "&nbsp"
    while rating > 0.67 do
      stars += '<i class="fa fa-star" fa-lg></i>'
      counter = counter + 1
      rating = rating - 1
    end
    if rating > 0.33
      stars += '<i class="fa fa-star-half-o" fa-lg></i>'
      counter = counter + 1
    end
      while counter< 5 do
      stars += '<i class="fa fa-star-o" fa-lg></i>'
      counter = counter + 1
    end
    stars.html_safe
  end


end

app/views/application/_flash_messages.html.haml
- if flash[:error]
  .pure-u-1.notice-error-container
    %i.fa.fa-exclamation-triangle.fa-2x
    %span.notice-text
      = flash[:error]

- if flash[:warning]
  .pure-u-1.notice-warning-container
    %i.fa.fa-exclamation-triangle.fa-2x
    %span.notice-text
      = flash[:warning]

- if flash[:success]
  .pure-u-1.notice-success-container
    %i.fa.fa-check-circle.fa-2x
    %span.notice-text
      = flash[:success]

app/views/application/_header.html.haml
%header.home-menu.pure-menu.pure-menu-horizontal
  =link_to render("logo"), '/', class: "pure-menu-heading #{current_page?('/') && !signed_in? ? 'logo-homepage' : nil}", id: "logo"
  %span.header-menu-items
    %ul.pure-menu-list
      - if signed_in?
        - # Signed in user Navbar
        %li.pure-menu-item
          Signed in as
          = link_to current_user.name, current_user, id: "header-username", class: gender_category_class
        %li.pure-menu-item
          = link_to edit_user_path(current_user) do
            %span.spin-fix
              = icon 'fa fa-cog fa-lg settings-icon'
        %li.pure-menu-item
          = link_to user_conversations_path(current_user) do
            = icon 'fa fa-lg fa-envelope-o'
        %li.pure-menu-item
          = link_to '/dashboard' do
            = icon 'fa fa-lg fa-briefcase'
        %li.pure-menu-item
          = link_to "Sign out", signout_path, method: "delete", id: 'sign-out-button', class: "btn btn-header btn-sign-out"
      - else                             
        - # Signed in user Navbar
        %li.pure-menu-item
          - unless current_page? signup_path
            = link_to "Sign up", signup_path, 
            id: 'sign-up-button', class: "btn btn-header #{current_page?('/') && !signed_in? ? 'btn-lg-header' : nil} btn-sign-up"
        %li.pure-menu-item
          - unless current_page? signin_path
            = link_to "Sign In", signin_path, 
            id: 'sign-in-button', class: "btn btn-header #{current_page?('/') && !signed_in? ? 'btn-lg-header' : nil} btn-sign-in"

app/views/application/_logo.html.haml
%span#logo-trans Trans
%span#logo-housing Housing